### ISSUE TITLE
HIP mallocMC_Example03 failed

### ISSUE THREAD

**Issue by saipavankalyan** [alpaka-group/mallocMC#168]
I am using the HIP ported mallocMC from this repo https://github.com/psychocoderHPC/mallocMC/tree/topic-hip-port

I am able to successfully build the application but the third example 'mallocMC_Example03' is failing as memory access fault both with HIP-clang and HIP-hcc.

Here is the error log for the same
Memory access fault by GPU node-2 (Agent handle: 0x72e100) on address 0x100000000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)

**Comment by sbastrakov** [comment]
Note: discussion started [here](https://github.com/ROCm-Developer-Tools/HIP/issues/1849#issuecomment-584609078) and moved into this issue as suggested by @psychocoderHPC .
