### ISSUE TITLE
Boost Static Assert & Pre 7.0 CUDA

### ISSUE THREAD

**Issue by slizzered** [alpaka-group/mallocMC#65]
This is the reminder for a work around for versions of CUDA before `7.0` and gcc before `4.8.2`, see #97
## 

Test, if there is a compiler bug related to -Wsign-compare:

The code

``` c++
uint32 x = ...;
BOOST_STATIC_ASSERT(x > 0);
```

produces a compiler warning about comparison between signed and unsigned.

None of the following does fix the warning on my test system:

``` c++
BOOST_STATIC_ASSERT(x > 0U);
BOOST_STATIC_ASSERT(x > (uint32)0);
BOOST_STATIC_ASSERT(x > static_cast<unsigned>(0));
```

However,  this works (strangely enough):

``` c++
BOOST_STATIC_ASSERT(static_cast<uint32>(x) > 0);
```

To be found in mallocMC:
- https://github.com/ComputationalRadiationPhysics/mallocMC/blob/dev/src/include/mallocMC/distributionPolicies/XMallocSIMD_impl.hpp#L80
- https://github.com/ComputationalRadiationPhysics/mallocMC/blob/dev/src/include/mallocMC/alignmentPolicies/Shrink_impl.hpp#L75-L77

Related: 
https://github.com/ComputationalRadiationPhysics/mallocMC/pull/64

**Comment by ax3l** [comment]
Isn't it normal that
```c++
uint32 x = ...;
BOOST_STATIC_ASSERT(x > 0);
``` produces a warning? `0` is an `int`, `0u` is an unsigned.

**Comment by slizzered** [comment]
Yes it is normal. The problem is that `BOOST_STATIC_ASSERT(x > 0U);` and the like don't work as I would expect

**Comment by ax3l** [comment]
ah, I over read the `None of the following  ...` !

**Comment by ax3l** [comment]
Sounds like a boost with nvcc problem to me.

Can you cross check with CUDA 7.5 and the latest boost release and open an issue in both issue trackers?

**Comment by slizzered** [comment]
I can no longer produce the warning (directly in the mentioned code segment) on my home machine (CUDA 7.0, gcc 5.2, Boost 1.58), which indicates that the bug has been resolved in the meantime.

That lead me to do some more testing:

| CUDA   |  Boost  | gcc   | status |
| ------ | --------| ------| ------ |
| 6.0    | 1.55.0  | 4.8.2 | :white_check_mark:     |
| 6.0    | 1.55.0  | 4.6.2 | :warning:   |
| 6.0    | 1.56.0  | 4.8.2 | :white_check_mark:     |
| 6.0    | 1.56.0  | 4.6.2 | :warning:   |
| 6.5    | 1.55.0  | 4.6.2 | :warning:   |
| 6.5    | 1.55.0  | 4.8.2 | :white_check_mark:   |
| 6.5    | 1.56.0  | 4.6.2 | :warning:   |
| 6.5    | 1.56.0  | 4.8.2 | :white_check_mark:   |
| 7.0    | 1.55.0  | 4.6.2 | :white_check_mark:     |
| 7.0    | 1.55.0  | 4.8.2 | :white_check_mark:     |
| 7.0    | 1.56.0  | 4.6.2 | :white_check_mark:     |
| 7.0    | 1.56.0  | 4.8.2 | :white_check_mark:     |

My result: The bug appears independently of Boost, but appears when combining **CUDA =< 6.5** and **gcc 4.6.2**. Using CUDA 7.0 or gcc 4.8.2 makes the warning disappear.

My approach would be to close the issue, but leave the code-workaround in place to ensure compatibility with older versions of CUDA/gcc. Objections?

**Comment by ax3l** [comment]
impressive test matrix, well done! :sparkles: 

you could add a `\todo` comment above the two affected lines so one can remove them in the future as soon as the requirements are `CUDA 7.0+` and `gcc 4.8.2+`.

**Comment by ax3l** [comment]
let us move this issue to `future` so we are more aware of it then just having an inline comment. What do you think?

**Comment by slizzered** [comment]
sure, sounds good :+1:

**Comment by psychocoderHPC** [comment]
Closed because the issue is outdated
