### ISSUE TITLE
Add halloc as a policy

### ISSUE THREAD

**Issue by slizzered** [alpaka-group/mallocMC#81]
1. Investigate what needs to be done to include [halloc](https://github.com/canonizer/halloc) as a policy into mallocMC
2. Add it
#### Wishlist
- Namespaces
- C++ templates instead of all the defines
- Allow to use only the fast algorithm and a single heap (remove CUDA default allocator)
- Make use of the whole device memory (currently limited to 3/4 of device memory)
- Destructor for halloc's heap (counterpart to `init()`-function)
- Trait for getAvailableSlots
- Maybe think about getAvailableSlots for halloc

**Comment by psychocoderHPC** [comment]
I tested in the past halloc but it was not in a state to be integrated into mallocMC. It looks like the project is not in development anymore.
